# =============================================================
# PHASE 6: PYTHON CODE GENERATOR
# Course: Compiler Design (TCS-601)
# Project: Code Genesis - C to Python Transpiler
# Team: Striver (CD-VI-T080)
# =============================================================
# Walks the ORIGINAL AST (not the IR) to produce clean, readable
# Python code.  Using the AST rather than the IR gives us much
# nicer output — proper indentation, real for-loops, etc.
#
# Mapping rules:
#   C type   → Python (types are dropped; Python is dynamic)
#   printf() → print()
#   for loop → while loop (since C-style for has no direct equiv)
#   {}       → indentation
#   &&, ||   → and, or
#   !        → not
# =============================================================

from lexer import Lexer
from parser import (Parser, ProgramNode, FunctionNode, BlockNode,
                    DeclarationNode, AssignNode, IfNode, WhileNode, ForNode,
                    ReturnNode, PrintNode, BinOpNode, UnaryOpNode,
                    NumberNode, StringNode, IdentifierNode, FunctionCallNode,
                    PointerTypeNode, DereferenceNode, AddressOfNode)


# ---------------------------------------------------------------
# OPERATOR MAPPING  (C → Python)
# ---------------------------------------------------------------
OP_MAP = {
    '&&': 'and',
    '||': 'or',
    '!':  'not',
    '==': '==', '!=': '!=',
    '<':  '<',  '>':  '>',
    '<=': '<=', '>=': '>=',
    '+':  '+',  '-':  '-',
    '*':  '*',  '/':  '//',   # integer division
    '%':  '%',
}


# ---------------------------------------------------------------
# CODE GENERATOR
# ---------------------------------------------------------------
class CodeGenerator:
    def __init__(self, indent_size=4):
        self.indent_size  = indent_size
        self._depth       = 0
        self._lines       = []

    def _indent(self):
        return ' ' * (self._depth * self.indent_size)

    def _emit(self, line=''):
        self._lines.append(self._indent() + line)

    def _emit_blank(self):
        self._lines.append('')

    # ---- Public entry ----

    def generate(self, ast):
        self._lines = []
        self._depth = 0
        self._emit('# Generated by Code Genesis (C → Python Transpiler)')
        self._emit('# Team Striver | Compiler Design TCS-601')
        self._emit_blank()
        self._emit("class Pointer:")
        self._depth += 1
        self._emit("def __init__(self, value, is_ref=False):")
        self._depth += 1
        self._emit("if is_ref: self.store = value")
        self._emit("else: self.store = [value]")
        self._depth -= 1
        self._emit("@property")
        self._emit("def val(self): return self.store[0]")
        self._emit("@val.setter")
        self._emit("def val(self, v): self.store[0] = v")
        self._depth -= 1
        self._emit_blank()
        self.visit(ast)
        # Append a main guard
        self._emit_blank()
        self._emit("if __name__ == '__main__':")
        self._depth += 1
        self._emit("main()")
        self._depth -= 1
        return '\n'.join(self._lines)

    def visit(self, node):
        method = f'visit_{type(node).__name__}'
        return getattr(self, method, self.generic_visit)(node)

    def generic_visit(self, node):
        return ''

    # ---- Visitors ----

    def visit_ProgramNode(self, node):
        for fn in node.functions:
            self.visit(fn)
            self._emit_blank()

    def visit_FunctionNode(self, node):
        params = ', '.join(p[1] for p in node.params)
        self._emit(f"def {node.name}({params}):")
        self._depth += 1
        self.visit(node.body)
        self._depth -= 1

    def visit_BlockNode(self, node):
        if not node.statements:
            self._emit('pass')
            return
        for stmt in node.statements:
            self.visit(stmt)

    def visit_DeclarationNode(self, node):
        if isinstance(node.var_type, PointerTypeNode):
            if node.value:
                val = self.visit(node.value)
                # If the value is already a Pointer/AddressOf, we don't need to box it twice
                self._emit(f"{node.name} = {val}")
            else:
                self._emit(f"{node.name} = Pointer(None)")
        else:
            if node.value:
                val = self.visit(node.value)
                self._emit(f"{node.name} = {val}")
            else:
                self._emit(f"{node.name} = 0")

    def visit_AssignNode(self, node):
        val = self.visit(node.value)
        if isinstance(node.target, DereferenceNode):
            target = self.visit(node.target.operand)
            self._emit(f"{target}.val = {val}")
        else:
            self._emit(f"{node.target.name} = {val}")

    def visit_IfNode(self, node):
        cond = self.visit(node.condition)
        self._emit(f"if {cond}:")
        self._depth += 1
        self.visit(node.then_block)
        self._depth -= 1
        if node.else_block:
            self._emit("else:")
            self._depth += 1
            self.visit(node.else_block)
            self._depth -= 1

    def visit_WhileNode(self, node):
        cond = self.visit(node.condition)
        self._emit(f"while {cond}:")
        self._depth += 1
        self.visit(node.body)
        self._depth -= 1

    def visit_ForNode(self, node):
        # Convert C for-loop to Python while-loop
        if node.init:
            self.visit(node.init)
        cond = self.visit(node.condition)
        self._emit(f"while {cond}:")
        self._depth += 1
        self.visit(node.body)
        self.visit(node.update)
        self._depth -= 1

    def visit_ReturnNode(self, node):
        val = self.visit(node.value)
        self._emit(f"return {val}")

    def visit_PrintNode(self, node):
        args = ', '.join(self.visit(a) for a in node.args)
        self._emit(f"print({args})")

    def visit_BinOpNode(self, node):
        left  = self.visit(node.left)
        right = self.visit(node.right)
        op    = OP_MAP.get(node.op, node.op)
        # Wrap in parens to preserve precedence
        return f"({left} {op} {right})"

    def visit_UnaryOpNode(self, node):
        operand = self.visit(node.operand)
        if node.op == '-':
            return f"(-{operand})"
        return operand

    def visit_DereferenceNode(self, node):
        operand = self.visit(node.operand)
        return f"{operand}.val"

    def visit_AddressOfNode(self, node):
        # In this simple transpiler, we assume address-of is used on a variable.
        # To make it work as a pointer, we need to wrap it.
        name = self.visit(node.operand)
        return f"Pointer({name}, is_ref=True)"

    def visit_NumberNode(self, node):
        return str(node.value)

    def visit_StringNode(self, node):
        # Translate C printf format specifiers minimally
        text = node.value
        return f'"{text}"'

    def visit_IdentifierNode(self, node):
        return node.name

    def visit_FunctionCallNode(self, node):
        args = ', '.join(self.visit(a) for a in node.args)
        # Map C stdlib calls → Python builtins
        name_map = {'printf': 'print', 'scanf': 'input'}
        name = name_map.get(node.name, node.name)
        return f"{name}({args})"


# ---------------------------------------------------------------
# STANDALONE TEST
# ---------------------------------------------------------------
if __name__ == '__main__':
    import os
    code = """
int factorial(int n) {
    if (n <= 1) {
        return 1;
    }
    return n * factorial(n - 1);
}

int main() {
    int x = 5;
    int result = factorial(x);
    printf("Factorial is");
    printf(result);
    return 0;
}
"""
    lexer  = Lexer(code)
    tokens = lexer.tokenize()
    parser = Parser(tokens)
    ast    = parser.parse()

    codegen = CodeGenerator()
    python_code = codegen.generate(ast)

    print("\n" + "="*55)
    print("PHASE 6: GENERATED PYTHON CODE")
    print("="*55)
    print(python_code)
    print("="*55)

    # Optionally save to file
    out_path = os.path.join(os.path.dirname(__file__), 'output.py')
    with open(out_path, 'w') as f:
        f.write(python_code)
    print(f"\n[✓] Python code saved to: {out_path}")
