# Generated by Code Genesis (C → Python Transpiler)
# Team Striver | Compiler Design TCS-601

def factorial(n):
    if (n <= 1):
        return 1
    return (n * factorial((n - 1)))

def main():
    i = 1
    while (i <= 5):
        f = factorial(i)
        print(i)
        print(f)
        i = (i + 1)
    return 0


if __name__ == '__main__':
    main()